### ISSUE TITLE
Publishing precompiled binaries?

### ISSUE THREAD

**Issue by ryyppy** [cristianoc/genFlow#26]
I don't know what's the easiest way, but I was thinking about trying out the same setup as Jared's [Reason Language Server](https://github.com/jaredly/reason-language-server) with circle CI and docker containers.

I am not entirely sure which npm package we should publish it to though

**Comment by bsansouci** [comment]
With bsb-native you don’t need docker btw, bsb just works on windows.

**Comment by ryyppy** [comment]
right, I didn't expect Windows to run on docker :-)
I saw that Jared is using appveyor for building windows artifacts, so I will use that as well...

For the rest, circleci will probably be fine

**Comment by ryyppy** [comment]
Done
