### ISSUE TITLE
Produce JS object types with property names that correspond to reserved words in Reason

### ISSUE THREAD

**Issue by jchavarri** [cristianoc/genFlow#37]
Currently it's not possible to do something like:

```rust
[@genFlow]
type action = {
  type: string,
};
```

Because `type` is reserved in Reason.

I was wondering if there could be some kind of mechanism to produce the following type in JS:

```js
export type action = {|type:string|};
```

even if in Reason we use some derivation of it that gets mangled during the process.

BuckleScript had a name mangling mechanism that converted `type__` (two underscores) into `type`. It can still be seen with `[@bs.deriving jsConverter]` ([example](https://reasonml.github.io/en/try?rrjsx=true&reason=NoAQRgzgdAJgpgJwJYDckDsDmACAVhAYQHt0VEAXRAXQChyBPABzmwEMBjcpE7AXmwDeNbNgbMA+uIBc2COWRYANDQC+AbhqagA)). I think the part of BuckleScript that does it is this [`lam_methname.ml`](https://github.com/jchavarri/bucklescript/blob/6bfa2aec6339375feb0fc842caeb985547c23500/jscomp/common/lam_methname.ml#L137).

Or maybe using something similar like `[@bs.as "type"]` like `bs.abstract`?

**Comment by cristianoc** [comment]
It will look like:
```reason
[@genFlow]
type action = {
  [@someAnnotation "type"] type_: string,
};
```
with some choice of `@someAnnotation`.
Technically, a new name is not required for the annotation, so one could just reuse `@genFlow` itself, as there's less to remember.
Or, `@genFlow.as`.
In fact, one could even allow both, with the same meaning, as if `@genFlow.as` were "inferred from the context" when just `@genFlow` is used.

**Comment by cristianoc** [comment]
@jchavarri now in master. See https://github.com/cristianoc/genFlow/commit/dfb55f08721c9a5ac64a137e85c8145c3d544ec4 for an example of usage.

**Comment by cristianoc** [comment]
Pushed and documented in README.

**Comment by jchavarri** [comment]
Works great, thanks!!
