### ISSUE TITLE
Need troubleshooting tips (expecting Greeting.re.js but not generated)

### ISSUE THREAD

**Issue by vonwao** [cristianoc/genFlow#38]
I followed the instructions in Readme:
- downloaded genflow.native and installed in usr/local/bin
- `export BS_CMT_POST_PROCESS_CMD=genflow.native`
- added genflowconfig.json file
- added ReactShim.shim.js file to source path
- tried adding `[@genType] or [@genFlow]` above `make` function 

I was confused about `[@genType] or [@genFlow]`.  However, I tried both and neither worked.

**Comment by cristianoc** [comment]
Sorry there were some changes in master (https://github.com/cristianoc/genFlow/commit/4043415f8fad9e563221bdd0cff77199332c6a13) and no release yet.
Would you try again and download release 0.9.0?

**Comment by vonwao** [comment]
Ok, thanks, will try it!

**Comment by cristianoc** [comment]
Closing optimistically.
If instead it still happens, feel free to reopen.

**Comment by vonwao** [comment]
Actually, later I discovered that the files were generated, but they ended up in a directory I didn't know about (lib/bs/...) so that was what went wrong.
