### ISSUE TITLE
Integration with bsb -clean-world

### ISSUE THREAD

**Issue by cristianoc** [cristianoc/genFlow#8]
https://github.com/BuckleScript/bucklescript/issues/2965

**Comment by cristianoc** [comment]
Done inhttps://github.com/cristianoc/genFlow/commit/3a64b36cff0d47d5d44d03c2dcb2b13d09eafd34.

**Comment by Coobaha** [comment]
@cristianoc I think calling `bsb -clean` or `bsb -clean-world` is not removing all `.gen.tsx` files but some of them
   
```
genType@2.39.0
bs-platform@5.1.0
```

```
  "gentypeconfig": {
    "language": "typescript",
    "importPath": "relative",
    "exportInterfaces": false,
    "module": "es6",
    "shims": {
      "ReasonReact": "ReactShim",
      "TsReact": "ReactShim",
      "React": "ReactShim",
      "ReactEvent": "ReactEvent",
      "Js": "Js",
      "Opaque": "OpaqueShim"
    },
    "namespace": true
  },
```

**Comment by cristianoc** [comment]
@Coobaha looks like the clean is done directly by bucklescript without calling genType.
++ @bobzhang 

See how in the example, projects, the clean is done "manually": https://github.com/cristianoc/genType/blob/master/examples/typescript-react-example/package.json#L16
